### ISSUE TITLE
default/optional logfile

### ISSUE THREAD

**Issue by gufmar** [vantuz-subhuman/cardano-testnet-examples#1]
Would it make sense to activate the writing of a log file by default or at least as an option?
Just to have some record about the created account and contract address, after having closed the console.

**Comment by gufmar** [comment]
solved by https://github.com/vantuz-subhuman/cardano-testnet-examples/tree/f92be866b6ded19684b7effa46ca45a834b00931

**Comment by vantuz-subhuman** [comment]
> solved by https://github.com/vantuz-subhuman/cardano-testnet-examples/tree/f92be866b6ded19684b7effa46ca45a834b00931

https://github.com/vantuz-subhuman/cardano-testnet-examples/pull/2 :)
